openapi: 3.0.3
info:
  title: Onfido Identity Verification API definition
  description: |-
    This document specifies an **Identity Verification RESTful API** for **WSO2 Identity Server**. The APIs provide the capability to verify an identity and retrive the verification status of identities. Moreover APIs are available to add/update/delete/patch identity verification providers.
  termsOfService: http://swagger.io/terms/
  contact:
    name: WSO2
    url: 'http://wso2.com/products/identity-server/'
    email: architecture@wso2.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: v1
servers:
  - url: 'https://{server-url}/t/{tenant-domain}/idv/onfido/v1'
    variables:
      tenant-domain:
        default: "carbon.super"
      server-url:
        default: "localhost:9443"
tags:
  - name: Identity Verification
    description: Identity Verification API
paths:
  /{idvp-id}/verify:
    post:
      tags:
        - Identity Verification
      summary: Get the identity verification claims of a user
      description: >
        This API provides the capability to perform Identity Verification through onfido.
      operationId: verify
      parameters:
        - in: header
          name: X-SHA2-Signature
          schema:
            type: string
          required: true
        - name: idvp-id
          in: path
          description: Id of the identity verification provider
          required: true
          schema:
            type: string
      requestBody:
        description: Verify an identity
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/verifyRequest'
      responses:
        '200':
          description: Ok
        '400':
          description: Invalid status value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
          example: AAA-00000
        message:
          type: string
          example: Some Error Message
        description:
          type: string
          example: Some Error Description
        traceId:
          type: string
          example: e0fbcfeb-3617-43c4-8dd0-7b7d38e13047
    verifyRequest:
      type: object
      properties:
        payload:
          type: object
          properties:
            resource_type:
              type: string
              example: "check"
            action:
              type: string
              example: "check.completed"
            object:
              type: object
              properties:
                id:
                  type: string
                  example: "1d74df5a-00c2-45b0-8519-cd0076aca3c1"
                status:
                  type: string
                  example: "complete"
                completed_at_iso8601:
                  type: string
                  format: date-time
                href:
                  type: string
      required:
        - identityVerificationProvider
        - properties
